quotes = [
    ("The only way to do great work is to love what you do.", "Steve Jobs"),
    ("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("Life is what happens when you're busy making other plans.", "John Lennon"),
    ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
    ("Believe you can and you're halfway there.", "Theodore Roosevelt"),
    ("You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    ("Whether you think you can or you think you can't, you're right.", "Henry Ford"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
    ("The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"),
    ("Act as if what you do makes a difference. It does.", "William James"),
    ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
    ("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    ("Keep your eyes on the stars, and your feet on the ground.", "Theodore Roosevelt"),
    ("Opportunities don't happen. You create them.", "Chris Grosser"),
    ("Try not to become a man of success. Rather become a man of value.", "Albert Einstein"),
    ("It is during our darkest moments that we must focus to see the light.", "Aristotle"),
    ("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
    ("You only live once, but if you do it right, once is enough.", "Mae West"),
    ("In the end, it's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"),
    ("Never let the fear of striking out keep you from playing the game.", "Babe Ruth"),
    ("Life is either a daring adventure or nothing at all.", "Helen Keller"),
    ("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas Edison"),
    ("You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", "Dr. Seuss"),
    ("If life were predictable it would cease to be life, and be without flavor.", "Eleanor Roosevelt"),
    ("If you look at what you have in life, you'll always have more.", "Oprah Winfrey"),
    ("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"),
    ("Money and success don't change people; they merely amplify what is already there.", "Will Smith"),
    ("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"),
    ("Not how long, but how well you have lived is the main thing.", "Seneca"),
    ("The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", "Henry Ford"),
    ("If you're not stubborn, you'll give up on experiments too soon.", "Jeff Bezos"),
    ("Definiteness of purpose is the starting point of all achievement.", "W. Clement Stone"),
    ("Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "Maya Angelou"),
    ("If you want to achieve excellence, you can get there today.", "Thomas J. Watson"),
    ("All our dreams can come true, if we have the courage to pursue them.", "Walt Disney"),
    ("Good, better, best. Never let it rest. Till your good is better and your better is best.", "St. Jerome"),
    ("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"),
    ("Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"),
    ("Just when the caterpillar thought the world was ending, he turned into a butterfly.", "Proverb"),
    ("An unexamined life is not worth living.", "Socrates"),
    ("Everything you've ever wanted is on the other side of fear.", "George Addair"),
    ("Dream big and dare to fail.", "Norman Vaughan"),
    ("You can't use up creativity. The more you use, the more you have.", "Maya Angelou"),
    ("Do one thing every day that scares you.", "Eleanor Roosevelt"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "Stephen Covey"),
    ("When everything seems to be going against you, remember that the airplane takes off against the wind.", "Henry Ford"),
    ("Too many of us are not living our dreams because we are living our fears.", "Les Brown"),
    ("I didn't fail the test. I just found 100 ways to do it wrong.", "Benjamin Franklin"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("It's not whether you get knocked down, it's whether you get up.", "Vince Lombardi"),
    ("People who are crazy enough to think they can change the world are the ones who do.", "Rob Siltanen"),
    ("Failure will never overtake me if my determination to succeed is strong enough.", "Og Mandino"),
    ("We may encounter many defeats but we must not be defeated.", "Maya Angelou"),
    ("Knowing is not enough; we must apply. Wishing is not enough; we must do.", "Johann Wolfgang Von Goethe"),
    ("Imagine your life is perfect in every respect; what would it look like?", "Brian Tracy"),
    ("We generate fears while we sit. We overcome them by action.", "Dr. Henry Link"),
    ("Security is mostly a superstition. Life is either a daring adventure or nothing.", "Helen Keller"),
    ("The man who has confidence in himself gains the confidence of others.", "Hasidic Proverb"),
    ("Nothing is impossible, the word itself says 'I'm possible'.", "Audrey Hepburn"),
    ("The bad news is time flies. The good news is you're the pilot.", "Michael Altshuler"),
    ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
    ("It is never too late to be what you might have been.", "George Eliot"),
    ("You become what you believe.", "Oprah Winfrey"),
    ("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"),
    ("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"),
    ("When you have a dream, you've got to grab it and never let go.", "Carol Burnett"),
    ("No matter what you're going through, there's a light at the end of the tunnel.", "Demi Lovato"),
    ("It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.", "William James"),
    ("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
    ("To see what is right and not do it is a lack of courage.", "Confucius"),
    ("Reading is to the mind as exercise is to the body.", "Joseph Addison"),
    ("The secret of change is to focus all of your energy not on fighting the old, but on building the new.", "Socrates"),
    ("Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"),
    ("The best way to predict the future is to create it.", "Peter Drucker"),
    ("Do what is right, not what is easy nor what is popular.", "Roy T. Bennett"),
    ("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    ("Spread love everywhere you go. Let no one ever come to you without leaving happier.", "Mother Teresa"),
    ("When you reach the end of your rope, tie a knot in it and hang on.", "Franklin D. Roosevelt"),
    ("Always remember that you are absolutely unique. Just like everyone else.", "Margaret Mead"),
    ("Don't judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson"),
    ("Wherever you go, go with all your heart.", "Confucius"),
    ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
    ("The journey of a thousand miles begins with one step.", "Lao Tzu"),
    ("Life is short, and it is here to be lived.", "Kate Winslet"),
    ("If you tell the truth, you don't have to remember anything.", "Mark Twain"),
    ("A friend is someone who knows all about you and still loves you.", "Elbert Hubbard"),
    ("To live is the rarest thing in the world. Most people just exist.", "Oscar Wilde"),
    ("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"),
    ("If you want to go fast, go alone. If you want to go far, go together.", "African Proverb"),
    ("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"),
    ("The purpose of our lives is to be happy.", "Dalai Lama"),
    ("Get busy living or get busy dying.", "Stephen King"),
    ("You have to believe in yourself when no one else does.", "Serena Williams"),
]
